import { ProtoRecord } from './proto_record';
import { EventBinding } from './event_binding';
import { ChangeDetectorDefinition } from './interfaces';
export declare class ChangeDetectorJITGenerator {
    private changeDetectionUtilVarName;
    private abstractChangeDetectorVarName;
    private _logic;
    private _names;
    private id;
    private changeDetectionStrategy;
    private records;
    private propertyBindingTargets;
    private eventBindings;
    private directiveRecords;
    private genConfig;
    typeName: string;
    constructor(definition: ChangeDetectorDefinition, changeDetectionUtilVarName: string, abstractChangeDetectorVarName: string);
    generate(): Function;
    generateSource(): string;
    _genPropertyBindingTargets(): string;
    _genDirectiveIndices(): string;
    _maybeGenHandleEventInternal(): string;
    _genEventBinding(eb: EventBinding): string;
    _genEventBindingEval(eb: EventBinding, r: ProtoRecord): string;
    _genMarkPathToRootAsCheckOnce(r: ProtoRecord): string;
    _genUpdatePreventDefault(eb: EventBinding, r: ProtoRecord): string;
    _maybeGenDehydrateDirectives(): string;
    _maybeGenHydrateDirectives(): string;
    _maybeGenAfterContentLifecycleCallbacks(): string;
    _maybeGenAfterViewLifecycleCallbacks(): string;
    _genRecord(r: ProtoRecord): string;
    _genDirectiveLifecycle(r: ProtoRecord): string;
    _genPipeCheck(r: ProtoRecord): string;
    _genReferenceCheck(r: ProtoRecord): string;
    _genChangeMarker(r: ProtoRecord): string;
    _genUpdateDirectiveOrElement(r: ProtoRecord): string;
    _genThrowOnChangeCheck(oldValue: string, newValue: string): string;
    _genCheckNoChanges(): string;
    _genAddToChanges(r: ProtoRecord): string;
    _maybeFirstInBinding(r: ProtoRecord): string;
    _maybeGenLastInDirective(r: ProtoRecord): string;
    _genOnCheck(r: ProtoRecord): string;
    _genOnInit(r: ProtoRecord): string;
    _genOnChange(r: ProtoRecord): string;
    _genNotifyOnPushDetectors(r: ProtoRecord): string;
}
